app {
    cache {
        capacity = 100
        ttl = 1 hour
        idle-ttl = 15 minutes
        refresh-after = 1 minutes
        recent-count = 100
        reaper-interval = 1 minute
        warmup-contest-ids = [551173]
    }

    http-server {
        host = "0.0.0.0"
        port = 8080
        max-header-size = 16KiB
        max-initial-line-length = 8KiB
        keep-alive = true
        idle-timeout = 60s
        graceful-shutdown-timeout = 20s
    }

    # Rate limiter: не более max запросов за interval
    rate-limiter {
        max = 1
        interval = 2 seconds
    }

    cf-api {
        key = ${KEY}
        secret = ${SECRET}
    }
}