app {
  contest-ids = [547763]

  handles = []

  # Интервал обновления данных
  poll-interval = 1 minute

  status-count = 50

  http-server {
    host = "0.0.0.0"

    port = 8080
  }

  group-code = "36RLDcYNaG"

  codeforces {
    api-key = ${KEY}
    api-secret = ${SECRET}
  }
}