app {
    tracking {
        contest-ids = [551173, 547763]
        handles = []
        poll-interval = 1 minute # Интервал обновления данных
        status-count = 50
    }

    http-server {
        host = "0.0.0.0"
        port = 8080
    }

    # Rate limiter: не более max запросов за interval
    rate-limiter {
        max = 1
        interval = 2 seconds
    }

    cf-api {
        key = ${KEY}
        secret = ${SECRET}
    }
}