name: Deploy (Manual)

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker-тег (например, dev-latest, master-latest, v1.0.0, mvp)'
        required: true
        default: 'dev-latest'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.5.0
        with:
          service_id: ${{ secrets.RENDER_DEV_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true